name       : meson
version    : 0.54.0
release    : 37
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.54.0/meson-0.54.0.tar.gz : dde5726d778112acbd4a67bb3633ab2ee75d33d1e879a6283a7b4a44c3363c27
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
