name       : meson
version    : 0.35.0
release    : 2
source     :
    - https://pypi.python.org/packages/ba/cd/9d1973f3f2777ec48398fc0dcbe0f776175b53b951de26eddcebb1c31730/meson-0.35.0.tar.gz : 8316f1b24f2b4375673b0b7fcd88f0402567bf1ac77e5caad88cb352ac8a9b70
license    : Apache-2.0
component  : programming.python
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
