name       : meson
version    : 0.48.0
release    : 21
source     :
    - https://github.com/mesonbuild/meson/archive/0.48.0.tar.gz : 9de95eff4577a9b2b258bdef7a544da3f7fedab94ac2eabc6bacfcd11ea4e07e
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
