name       : meson
version    : 0.55.3
release    : 41
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.55.3/meson-0.55.3.tar.gz : 6bed2a25a128bbabe97cf40f63165ebe800e4fcb46db8ab7ef5c2b5789f092a5
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
