name       : meson
version    : 0.56.0
release    : 42
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.56.0/meson-0.56.0.tar.gz : 291dd38ff1cd55fcfca8fc985181dd39be0d3e5826e5f0013bf867be40117213
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
