name       : meson
version    : 0.48.1
release    : 22
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.48.1/meson-0.48.1.tar.gz : 425d12edbb81498314926afa93a3eb2fca4ca6929cbe0f8abeb6ab45d1d9fa8f
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
