name       : meson
version    : 0.55.1
release    : 40
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.55.1/meson-0.55.1.tar.gz : 3b5741f884e04928bdfa1947467ff06afa6c98e623c25cef75adf71ca39ce080
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
