name       : meson
version    : 0.47.2
release    : 20
source     :
    - https://github.com/mesonbuild/meson/archive/0.47.2.tar.gz : 69e251dc169e82e3d3235643c873167764d63020515d9ca837ea95ff021f2c83
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
