name       : meson
version    : 0.50.1
release    : 29
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.50.1/meson-0.50.1.tar.gz : f68f56d60c80a77df8fc08fa1016bc5831605d4717b622c96212573271e14ecc
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
