name       : meson
version    : 0.59.2
release    : 51
source     :
    - https://github.com/mesonbuild/meson/archive/refs/tags/0.59.2.tar.gz : e6d5ccd503d41f938f6cfc4dc9e7326ffe28acabe091b1ff0c6535bdf09732dd
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
