name       : meson
version    : 0.49.1
release    : 25
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.49.1/meson-0.49.1.tar.gz : e90c8ee46109d3b9d9a12c76c65811d4a7f7e18503f780eb301866e43d9052cb
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
