name       : meson
version    : 0.57.2
release    : 46
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.57.2/meson-0.57.2.tar.gz : 3a83e7b1c5de94fa991ec34d9b198d94f38ed699d3524cb0fdf3b99fd23d4cc5
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
