name       : meson
version    : 0.58.0
release    : 47
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.58.0/meson-0.58.0.tar.gz : f4820df0bc969c99019fd4af8ca5f136ee94c63d8a5ad67e7eb73bdbc9182fdd
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
