name       : meson
version    : 0.45.0
release    : 15
source     :
    - https://github.com/mesonbuild/meson/archive/0.45.0.tar.gz : 3e7a787b146e7b04cfb2f8a920e406acdc75044f3d1f397461bec933274424c1
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
