name       : meson
version    : 0.49.2
release    : 26
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.49.2/meson-0.49.2.tar.gz : ef9f14326ec1e30d3ba1a26df0f92826ede5a79255ad723af78a2691c37109fd
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
