name       : meson
version    : 0.50.0
release    : 28
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.50.0/meson-0.50.0.tar.gz : 2a1bc42dda58206fb922cda5e1ca95cc03ad126321d26acc47d3493ec4e7021f
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
