name       : meson
version    : 0.62.2
release    : 56
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.62.2/meson-0.62.2.tar.gz : a7669e4c4110b06b743d57cc5d6432591a6677ef2402139fe4f3d42ac13380b0
homepage   : https://mesonbuild.com/
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    Meson® is a project to create the best possible next-generation build system.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
