name       : meson
version    : 0.51.1
release    : 30
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.51.1/meson-0.51.1.tar.gz : f27b7a60f339ba66fe4b8f81f0d1072e090a08eabbd6aa287683b2c2b9dd2d82
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
