name       : meson
version    : 0.55.0
release    : 39
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.55.0/meson-0.55.0.tar.gz : 0a1ae2bfe2ae14ac47593537f93290fb79e9b775c55b4c53c282bc3ca3745b35
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
