name       : meson
version    : 0.49.0
release    : 24
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.49.0/meson-0.49.0.tar.gz : fb0395c4ac208eab381cd1a20571584bdbba176eb562a7efa9cb17cace0e1551
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
