name       : meson
version    : 0.38.1
release    : 5
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.38.1/meson-0.38.1.tar.gz : dcb05349b32427924fa2a258a5e23e40e09c1bf9dd09919198c3a2ae1c38ba53
license    : Apache-2.0
component  : programming.python
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
