name       : meson
version    : 0.56.2
release    : 43
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.56.2/meson-0.56.2.tar.gz : 3cb8bdb91383f7f8da642f916e4c44066a29262caa499341e2880f010edb87f4
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
