name       : meson
version    : 0.41.0
release    : 9
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.41.0/meson-0.41.0.tar.gz : 99a27fca44c07cebd8b954bd219fd9c5ef89f3aeb84eed462f6b6f46db2a3359
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
