name       : meson
version    : 0.33.0
release    : 1
source     :
    - https://pypi.python.org/packages/ec/51/df65c73f957375bbd814bb0353213d0422d07fe538b92a2a23fa683e499b/meson-0.33.0.tar.gz : 2417fd27cbb1e9b1006fe9e5a1f3896285d4c925ffffdf9478638b5fe3ea7fc5
license    : Apache-2.0
component  : programming.python
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
