name       : meson
version    : 0.40.1
release    : 8
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.40.1/meson-0.40.1.tar.gz : 890ce46e713ea0d061f8203c99fa7d38645354a62e4c207c38ade18db852cbf5
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
