name       : meson
version    : 0.60.2
release    : 52
source     :
    - https://github.com/mesonbuild/meson/archive/refs/tags/0.60.2.tar.gz : fc7c2f315b5b63fee0414b0b94b5a7d0e9c71c8c9bb8487314eb5a9a33984b8d
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
