name       : meson
version    : 0.42.1
release    : 11
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.42.1/meson-0.42.1.tar.gz : 30bdded6fefc48211d30818d96dd34aae56ee86ce9710476f501bd7695469c4b
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
