name       : meson
version    : 0.51.2
release    : 33
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.51.2/meson-0.51.2.tar.gz : 23688f0fc90be623d98e80e1defeea92bbb7103bf9336a5f5b9865d36e892d76
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
