name       : meson
version    : 0.47.0
release    : 18
source     :
    - https://github.com/mesonbuild/meson/archive/0.47.0.tar.gz : 1804c3c5a04e0a9c0d073cc85003f2fad052a5f12e98e8afab7cb396248a7872
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
