name       : meson
version    : 0.62.1
release    : 55
source     :
    - https://github.com/mesonbuild/meson/archive/refs/tags/0.62.1.tar.gz : 9fb52e66dbc613479a5f70e46cc2e8faf5aa65e09313f2c71fa63b8afd018107
homepage   : https://mesonbuild.com/
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    Meson® is a project to create the best possible next-generation build system.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
