name       : meson
version    : 0.36.0
release    : 3
source     :
    - https://pypi.python.org/packages/9d/d1/368905f5b6f64617844d2d25e4b5a150b56991e01b8691c31be87cba3ded/meson-0.36.0.tar.gz : 17e3fb4ac697c2bd2ba7f555e5830ac13257b2250f4922e6bec504303b2830d5
license    : Apache-2.0
component  : programming.python
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
