name       : meson
version    : 0.60.3
release    : 54
source     :
    - https://github.com/mesonbuild/meson/archive/refs/tags/0.60.3.tar.gz : 6c191a9b4049e0c9a2a7d1275ab635b91f6ffec1912d75df4c5ec6acf35f74fe
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
