name       : meson
version    : 0.45.1
release    : 16
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.45.1/meson-0.45.1.tar.gz : 4d0bb0dbb1bb556cb7a4092fdfea3d6e76606bd739a4bc97481c2d7bc6200afb
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
