name       : meson
version    : 0.57.0
release    : 44
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.57.0/meson-0.57.0.tar.gz : 7ccb75fe1a4d404bcab86e72678abc7f75793401aa9054f881a4eb3cb990f5d9
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
