name       : meson
version    : 0.52.0
release    : 35
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.52.0/meson-0.52.0.tar.gz : d60f75f0dedcc4fd249dbc7519d6f3ce6df490033d276ef1cf27453ef4938d32
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
