name       : meson
version    : 0.39.1
release    : 6
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.39.1/meson-0.39.1.tar.gz : 44885ccfef94d3d4afb1053fa6673ed130d3093fc9e9f6624d08161d8a385220
license    : Apache-2.0
component  : programming.python
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
