name       : meson
version    : 0.59.1
release    : 50
source     :
    - https://github.com/mesonbuild/meson/archive/refs/tags/0.59.1.tar.gz : f256eb15329a6064f8cc1f23b29de1fa8d21e324f939041e1a4efe77cf1362ef
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
