name       : meson
version    : 0.47.1
release    : 19
source     :
    - https://github.com/mesonbuild/meson/archive/0.47.1.tar.gz : c227ae37c1d4c8fc1531d536b38ff1fbf7afb08c59fc54a5321645164e5f92a8
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
