name       : meson
version    : 0.53.2
release    : 36
source     :
    - https://github.com/mesonbuild/meson/releases/download/0.53.2/meson-0.53.2.tar.gz : 3e8f830f33184397c2eb0b651ec502adb63decb28978bdc84b3558d71284c21f
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
