name       : meson
version    : 1.1.0
release    : 57
source     :
    - https://github.com/mesonbuild/meson/releases/download/1.1.0/meson-1.1.0.tar.gz : d9616c44cd6c53689ff8f05fc6958a693f2e17c3472a8daf83cee55dabff829f
homepage   : https://mesonbuild.com/
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    Meson® is a project to create the best possible next-generation build system.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
