name       : meson
version    : 0.48.2
release    : 23
source     :
    - https://github.com/mesonbuild/meson/archive/0.48.2.tar.gz : 1daac2fd3d97f26a28f6f7e9addccc85a526a471dbd836613ce34130f69adcc0
license    : Apache-2.0
component  : system.devel
summary    : A high performance build system
description: |
    A high performance build system
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - ninja
build      : |
    %python3_setup
install    : |
    %python3_install
